### ISSUE TITLE
[BUG] Cannot receive response from GET request for list of all devtips

### ISSUE THREAD

**Issue by at-the-vr** [Pradumnasaraf/OpenSource-API#50]
### Description

Hey Pradumna, while exploring your API I found that the GET `/api/devtip` endpoint results in no response in its current state and keeps on waiting.

API Client in Use: Thunder Client v2.6.0
Browser/OS in Use: Chrome/Windows 10 (I am running this on Localhost setup at current time)

The `Home page` endpoint was working pretty smooth during my exploration. Even the `/api/devtip/:id` endpoint was giving me the error response for incorrect ids.

**Comment by Pradumnasaraf** [comment]
Hey, 

Thank you for opening the issue. That was weird behaviour from Vercel's side. I have redeployed the API. Can you test again those Routes?

**Comment by at-the-vr** [comment]
I gave a couple of tries and still getting no response, this is only specific to the GET `/api/devtip` request. All other endpoints do give me a response

**Comment by at-the-vr** [comment]
I gave it a try yesterday night and this morning as well, still not getting any response ? am I doing it wrong ? I believe the whole URI would be `http://localhost:9009/api/devtip` with a GET method right ?

**Comment by Pradumnasaraf** [comment]
How are you running with Docker or local setup? If you have a local setup check if the Mongo is running or not and copy env. I checked on two systems everything is fine. Also, you should get this message in the console.

<img width="668" alt="Screenshot 2023-04-09 at 10 42 18 AM" src="https://user-images.githubusercontent.com/51878265/230755608-af85396e-b038-4ae7-af0d-642823536ab3.png">

Also, here the testing video


https://user-images.githubusercontent.com/51878265/230755593-7dc040e8-52c1-43ae-ae93-2725e435b203.mov

**Comment by at-the-vr** [comment]
Managed to found that I am not getting `Successfully connected to MongoDB`  cause of this Issue ⏬ 
![image](https://user-images.githubusercontent.com/88548999/230756327-559fa70c-bfe3-4588-804b-abefbf603e4d.png)

- This is all in a localhost setup without the `docker compose method`
- Changing the MONGDB_URL (suggestion taken from Stack Overflow) results in ` code: 'ERR_INVALID_URL' `. Not sure how to diagnose this 😞

**Comment by Pradumnasaraf** [comment]
> Managed to found that I am not getting `Successfully connected to MongoDB` cause of this Issue ⏬ ![image](https://user-images.githubusercontent.com/88548999/230756327-559fa70c-bfe3-4588-804b-abefbf603e4d.png)
> 
> * This is all in a localhost setup without the `docker compose method`
> * Changing the MONGDB_URL (suggestion taken from Stack Overflow, MONGODB Forums) results in `code: 'ERR_INVALID_URL'`. Not sure how to diagnose this 😞

I think your Mongo is not running check the solution on how to do that.

**Comment by at-the-vr** [comment]
that's true, so i went with the docker method and what i get is this ⬇️ 
![image](https://user-images.githubusercontent.com/88548999/230758941-ba32ce2c-9978-48d4-b123-e9b12e66d91a.png)

Is that meant to do so, cuz your response has couple of devtips

**Comment by Pradumnasaraf** [comment]
> Is that meant to do so, cuz your response has couple of devtips

Yes, because I have added some via post request. You can also add data to DB by creating a POST req path `/api/devtip` with the body

```json
{
 "message": "Your message/devtip"
}
```

I am closing this as this is resolved. Also, when you are able to add data and get data let me know by commenting

**Comment by at-the-vr** [comment]
> Managed to found that I am not getting `Successfully connected to MongoDB` cause of this Issue ⏬ ![image](https://user-images.githubusercontent.com/88548999/230756327-559fa70c-bfe3-4588-804b-abefbf603e4d.png)
> 
> * This is all in a localhost setup without the `docker compose method`
> * Changing the MONGDB_URL (suggestion taken from Stack Overflow, MONGODB Forums) results in `code: 'ERR_INVALID_URL'`. Not sure how to diagnose this 😞

I was bit confused with the localhost method, cause I can still receive the `MongooseServerSelectionError: connect ECONNREFUSED ::1:27017` error and from what I have tried, the Docker method and the localhost method are completely separate right ?

**Comment by Pradumnasaraf** [comment]
> I was bit confused with the localhost method, cause I can still receive the MongooseServerSelectionError: connect ECONNREFUSED ::1:27017 error and from what I have tried, the Docker method and the localhost method are completely separate right ?

Yes, when running an app and MongoDB inside a container, so different from local dev, not Localhost. 'Localhost' refers to running the website on our local system. However, we still use the 'localhost' URL to talk to the API even when running with Docker. I think your issue might be with MongoDB. It might not be installed or try reinstalling it.

> I followed the readme, copied the env variables, installed the dependencies with npm i, ran the server with npm run dev, what's the reason that it refuses for connection ?

Mongo issue as I told

**Comment by at-the-vr** [comment]
Hi Pradumna I just wanted to summarize the diagnosis for this Issue, Docker is the best way to run this Application right ? cause performing localhost setup would not connect MongoDB with App

**Comment by Pradumnasaraf** [comment]
> Docker is the best way to run this Application right ?

Yes

> cause performing localhost setup would not connect MongoDB with App

No, you can run Mongo locally as well. Here is the link - https://www.mongodb.com/try/download/community
